export const USER_POST_REQUEST = "USER_POST_REQUEST"
export const USER_POST_SUCCESS = "USER_POST_SUCCESS"
export const USER_POST_FAILURE = "USER_POST_FAILURE"

export const USER_GET_POSTS_REQUEST = "USER_GET_POSTS_REQUEST"
export const USER_GET_POSTS_SUCCESS = "USER_GET_POSTS_SUCCESS"
export const USER_GET_POSTS_FAILURE = "USER_GET_POSTS_FAILURE"

export const USER_UPDATE_POSTS_REQUEST = "USER_UPDATE_POSTS_REQUEST"
export const USER_UPDATE_POSTS_SUCCESS = "USER_UPDATE_POSTS_SUCCESS"
export const USER_UPDATE_POSTS_FAILURE = "USER_UPDATE_POSTS_FAILURE"

export const USER_DELETE_POSTS_REQUEST = "USER_DELETE_POSTS_REQUEST"
export const USER_DELETE_POSTS_SUCCESS = "USER_DELETE_POSTS_SUCCESS"
export const USER_DELETE_POSTS_FAILURE = "USER_DELETE_POSTS_FAILURE"